package com.demo.medicaltourismapp.model.enums;

public enum CityEnum {
    ISTANBUL, ANKARA, IZMIR, BURSA, ANTALYA, ADANA, BALIKESIR, ESKISEHIR,
    BERLIN, MUNICH, HAMBURG, PRAGUE, VIENNA, ATHENS, LISBON,
    LONDON, PARIS, DUBROVNIK, MOSCOW, ST_PETERSBURG, KYIV, SOFIA
}
